#!/usr/bin/env python3
from pyrogram.handlers import MessageHandler, CallbackQueryHandler
from pyrogram.filters import command, regex

from bot import LOGGER, bot
from bot.helper.mirror_utils.upload_utils.gdriveTools import GoogleDriveHelper
from bot.helper.telegram_helper.message_utils import sendMessage, editMessage
from bot.helper.telegram_helper.filters import CustomFilters
from bot.helper.telegram_helper.bot_commands import BotCommands
from bot.helper.telegram_helper.button_build import ButtonMaker
from bot.helper.ext_utils.bot_utils import (
    sync_to_async,
    new_task,
    get_telegraph_list,
    checking_access,
)
from bot.helper.themes import BotTheme


# Callback data is deliberately kept short. The query itself lives here so
# searches containing spaces and non-reply commands work after button clicks.
_list_queries = {}


def _parse_bool(value):
    return str(value).lower() == "true"


async def list_buttons(user_id, is_recursive=True, user_token=False, query_id=0):
    buttons = ButtonMaker()
    buttons.ibutton(
        f"{'✅️' if user_token else '❌️'} User Token",
        f"list_types {user_id} {query_id} ut {is_recursive} {user_token}",
        "header",
    )
    buttons.ibutton(
        f"{'✅️' if is_recursive else '❌️'} Recursive",
        f"list_types {user_id} {query_id} rec {is_recursive} {user_token}",
        "header",
    )
    buttons.ibutton(
        "📁 𝐎ɴʟʏ 𝐅ᴏʟᴅᴇʀs",
        f"list_types {user_id} {query_id} folders {is_recursive} {user_token}",
    )
    buttons.ibutton(
        "📄 𝐎ɴʟʏ 𝐅ɪʟᴇs",
        f"list_types {user_id} {query_id} files {is_recursive} {user_token}",
    )
    buttons.ibutton(
        "📋 𝐁ᴏᴛʜ",
        f"list_types {user_id} {query_id} both {is_recursive} {user_token}",
    )
    buttons.ibutton(
        "❌ 𝐂ᴀɴᴄᴇʟ",
        f"list_types {user_id} {query_id} cancel",
        "footer",
    )
    return buttons.build_menu(2)


async def _list_drive(
    key, message, user_id, item_type, is_recursive, user_token
):
    LOGGER.info("GDrive List: %s", key)
    gdrive = GoogleDriveHelper(
        user_id=user_id if user_token else None,
        use_user_token=user_token,
    )
    try:
        telegraph_content, contents_no = await sync_to_async(
            gdrive.drive_list,
            key,
            isRecursive=is_recursive,
            itemType=item_type,
            userId=user_id,
        )
    except Exception as err:
        LOGGER.error("GDrive list failed: %s", err, exc_info=True)
        return await editMessage(
            message,
            f"<b>Drive search failed:</b> <code>{str(err).replace('<', '').replace('>', '')}</code>",
        )
    if telegraph_content:
        try:
            button = await get_telegraph_list(telegraph_content)
        except Exception as err:
            await editMessage(message, str(err))
            return
        await editMessage(
            message,
            BotTheme("LIST_FOUND", NO=contents_no, NAME=key),
            button,
        )
    else:
        await editMessage(message, BotTheme("LIST_NOT_FOUND", NAME=key))


@new_task
async def select_type(_, query):
    user_id = query.from_user.id
    message = query.message
    data = query.data.split()
    if len(data) < 3 or user_id != int(data[1]):
        return await query.answer(text="𝐍ᴏᴛ 𝐘ᴏᴜʀs!", show_alert=True)

    # Current callbacks: list_types uid message_id action recursive user_token
    # The fallback keeps buttons generated by an older running process usable.
    if len(data) >= 4 and data[2].isdigit():
        query_id = int(data[2])
        action = data[3]
        is_recursive = _parse_bool(data[4]) if len(data) >= 5 else True
        user_token = _parse_bool(data[5]) if len(data) >= 6 else False
        key = _list_queries.get(query_id)
    else:
        query_id = 0
        action = data[2]
        is_recursive = _parse_bool(data[3]) if len(data) > 3 else True
        user_token = False
        key = None

    if not key and message.reply_to_message:
        reply_text = (
            message.reply_to_message.text
            or message.reply_to_message.caption
            or ""
        )
        if reply_text:
            key = reply_text.split(maxsplit=1)[-1].strip()
    if not key:
        return await editMessage(
            message,
            "<b>List session expired. Please run the command again.</b>",
        )

    if action == "rec":
        await query.answer()
        buttons = await list_buttons(
            user_id, not is_recursive, user_token, query_id
        )
        return await editMessage(
            message,
            "<b>𝐂ʜᴏᴏsᴇ ᴅʀɪᴠᴇ 𝐥ɪsᴛ ᴏᴘᴛɪᴏɴs:</b>",
            buttons,
        )

    if action == "ut":
        token_path = f"tokens/{user_id}.pickle"
        if not ospath.exists(token_path):
            return await query.answer(
                "No user token.pickle is uploaded.", show_alert=True
            )
        await query.answer()
        buttons = await list_buttons(
            user_id, is_recursive, not user_token, query_id
        )
        return await editMessage(
            message,
            "<b>𝐂ʜᴏᴏsᴇ ᴅʀɪᴠᴇ 𝐥ɪsᴛ ᴏᴘᴛɪᴏɴs:</b>",
            buttons,
        )

    if action == "cancel":
        await query.answer()
        _list_queries.pop(query_id, None)
        return await editMessage(message, "<b>𝐋ɪsᴛ ʜᴀs ʙᴇᴇɴ ᴄᴀɴᴄᴇʟᴇᴅ!</b>")

    await query.answer()
    await editMessage(message, BotTheme("LIST_SEARCHING", NAME=key))
    await _list_drive(
        key, message, user_id, action, is_recursive, user_token
    )
    _list_queries.pop(query_id, None)


async def drive_list(_, message):
    args = message.text.split() if message.text else ["/cmd"]
    if len(args) == 1:
        return await sendMessage(
            message,
            "<i>𝐒ᴇɴᴅ ᴀ sᴇᴀʀᴄʜ ᴋᴇʏ ᴀʟᴏɴɢ ᴡɪᴛʜ ᴄᴏᴍᴍᴀɴᴅ</i>",
        )
    user_id = message.from_user.id
    msg, btn = await checking_access(user_id)
    if msg is not None:
        await sendMessage(message, msg, btn.build_menu(1))
        return
    key = " ".join(args[1:]).strip()
    sent = await sendMessage(
        message,
        "<b>𝐂ʜᴏᴏsᴇ ᴅʀɪᴠᴇ 𝐥ɪsᴛ ᴏᴘᴛɪᴏɴs:</b>",
        await list_buttons(user_id),
        "IMAGES",
    )
    if hasattr(sent, "id"):
        _list_queries[sent.id] = key
        await editMessage(
            sent,
            "<b>𝐂ʜᴏᴏsᴇ ᴅʀɪᴠᴇ 𝐥ɪsᴛ ᴏᴘᴛɪᴏɴs:</b>",
            await list_buttons(user_id, query_id=sent.id),
        )


bot.add_handler(
    MessageHandler(
        drive_list,
        filters=command(BotCommands.ListCommand)
        & CustomFilters.authorized
        & ~CustomFilters.blacklisted,
    )
)
bot.add_handler(CallbackQueryHandler(select_type, filters=regex("^list_types")))
