#!/usr/bin/env python3
from re import search as re_search

from aiofiles.os import remove as aioremove
from pyrogram.handlers import MessageHandler
from pyrogram.filters import command
from pyrogram.errors import (
    PhotoInvalidDimensions,
    WebpageCurlFailed,
    MediaEmpty,
    MediaCaptionTooLong,
)

try:
    # Lets us pin exactly which URL Telegram generates a link-preview
    # thumbnail for, regardless of how many other links are in the text.
    # Older Pyrogram builds don't have this type — handled via fallback.
    from pyrogram.types import LinkPreviewOptions
except ImportError:
    LinkPreviewOptions = None

from bot import bot, LOGGER, config_dict
from bot.helper.telegram_helper.filters import CustomFilters
from bot.helper.telegram_helper.bot_commands import BotCommands
from bot.helper.telegram_helper.message_utils import sendMessage, editMessage
from bot.helper.ext_utils.bot_utils import new_task, download_image_url
from bot.helper.ext_utils.spidy_api import fetch_spidy_assets
from bot.helper.ext_utils.tmdb_api import fetch_tmdb_logo


async def _reply_photo_with_caption(message, photo, text):
    """reply_photo with the caption drawn ABOVE the image (matches the
    reference bot). Falls back to a normal caption-below-photo message if
    the running Pyrogram build doesn't know the `show_caption_above_media`
    kwarg yet — still a single message either way."""
    try:
        return await message.reply_photo(
            photo=photo,
            caption=text,
            show_caption_above_media=True,
            disable_notification=True,
        )
    except TypeError:
        return await message.reply_photo(
            photo=photo,
            caption=text,
            disable_notification=True,
        )


async def _send_poster_message(message, text, hero_photo):
    """Send the whole result — text + hero image — as ONE message (photo
    with the formatted text as its caption), so it never shows up as a
    separate/disconnected bubble like the old two-message approach did.
    Returns None (instead of raising) only when the caption is too long
    for a single message, so the caller can fall back to two messages
    rather than silently dropping the link list."""
    try:
        return await _reply_photo_with_caption(message, hero_photo, text)
    except MediaCaptionTooLong:
        return None
    except (PhotoInvalidDimensions, WebpageCurlFailed, MediaEmpty):
        # TMDB/landscape URLs occasionally fail Telegram's direct-URL fetch
        # (bad dimensions, curl error, etc.) — download locally and resend
        # as a real photo instead of letting Telegram fall back to sending
        # it as a generic file/document (which shows a "289.5 KB ..." file
        # header instead of a clean photo).
        des_dir = await download_image_url(hero_photo)
        try:
            return await _reply_photo_with_caption(message, des_dir, text)
        except MediaCaptionTooLong:
            return None
        finally:
            await aioremove(des_dir)


async def _send_hero_photo(chat_id, photo_url):
    """Send the hero image as a plain, independent message — used only as
    the two-message fallback when the caption is too long for one message."""
    try:
        await bot.send_photo(chat_id=chat_id, photo=photo_url, disable_notification=True)
    except (PhotoInvalidDimensions, WebpageCurlFailed, MediaEmpty):
        des_dir = await download_image_url(photo_url)
        try:
            await bot.send_photo(chat_id=chat_id, photo=des_dir, disable_notification=True)
        finally:
            await aioremove(des_dir)


async def _send_with_blockquoted_preview(message, text, hero_photo):
    """Reference-bot look: whole result is ONE plain text message, and the
    hero image is a link-preview thumbnail generated by Telegram for a
    hidden link placed inside the last <blockquote> — so it gets the exact
    same bordered/quoted styling as every other section instead of showing
    up as a bare, unbordered photo attachment.
    Raises if the running Pyrogram build can't pin the preview to this
    specific URL — caller must fall back to attaching the photo directly."""
    if LinkPreviewOptions is None:
        raise TypeError("LinkPreviewOptions not supported by this Pyrogram build")
    preview_text = text + (
        f"<blockquote><a href='{hero_photo}'>\u2063</a></blockquote>"
    )
    return await message.reply(
        preview_text,
        quote=True,
        disable_notification=True,
        link_preview_options=LinkPreviewOptions(
            url=hero_photo,
            show_above_text=False,
            prefer_large_media=True,
        ),
    )


@new_task
async def poster_cmd(_, message):
    args = message.text.split(maxsplit=1)
    if len(args) < 2 or not args[1].strip():
        await sendMessage(
            message,
            "<b>𝐔sᴀɢᴇ:</b> <code>/{0} movie name [year]</code>\n"
            "<b>𝐄x:</b> <code>/{0} pk 2014</code>".format(
                BotCommands.PosterCommand
            ),
        )
        return

    query = args[1].strip()
    year = None
    year_match = re_search(r"\b(19|20)\d{2}\b$", query)
    title = query
    if year_match:
        year = year_match.group(0)
        title = query[: year_match.start()].strip()

    status = await sendMessage(message, "<i>𝐒ᴇᴀʀᴄʜɪɴɢ 𝐏ᴏsᴛᴇʀs...</i>")

    api_key = config_dict.get("SPIDY_API_KEY", "")
    try:
        assets = await fetch_spidy_assets(title, api_key, year=year)
    except Exception as e:
        LOGGER.error(f"Poster Command: Spidy API error for '{title}': {e}")
        assets = None

    tmdb_key = config_dict.get("TMDB_API_KEY", "")
    tmdb_result = None
    if tmdb_key:
        try:
            tmdb_result = await fetch_tmdb_logo(title, tmdb_key, year=year)
        except Exception as e:
            LOGGER.error(f"Poster Command: TMDB API error for '{title}': {e}")
            tmdb_result = None

    # ALL PNG clear logos TMDB has (every language) — not just one.
    logos = tmdb_result["logos"] if tmdb_result else []

    if not assets and not logos:
        await editMessage(
            status,
            f"<b>❌ 𝐍ᴏ 𝐏ᴏsᴛᴇʀs 𝐅ᴏᴜɴᴅ ғᴏʀ:</b> <i>{title}{f' ({year})' if year else ''}</i>",
        )
        return

    if not assets:
        assets = {
            "title": tmdb_result["title"],
            "year": tmdb_result["year"],
            "landscape": [],
            "poster": [],
        }

    tag = message.from_user.mention
    display_title = assets["title"]
    if assets.get("year"):
        display_title += f" ({assets['year']})"

    text = (
        "<blockquote>"
        "<b><emoji id=5424818078833715060>🎬</emoji> 𝐌ᴏᴠɪᴇ:</b>"
        f"{display_title}</blockquote>\n\n"
    )

    if assets["landscape"]:
        text += "<b><emoji id=5334544901428229844>🖼</emoji> 𝐄ɴɢʟɪsʜ 𝐋ᴀɴᴅsᴄᴀᴘᴇ:</b>\n<blockquote expandable>"
        for i, url in enumerate(assets["landscape"], 1):
            text += f"{i}. <a href='{url}'>Click Here</a>\n"
        text += "</blockquote>\n"

    # Only added when TMDB actually has PNG clear logo(s) for this title —
    # never a placeholder/broken link when none is found. Every language
    # TMDB has a logo for is listed, matching how other bots present it.
    if logos:
        text += "<b><emoji id=5427168083074628963>🎨</emoji> 𝐋ᴏɢᴏs 𝐏ɴɢ:</b>\n<blockquote expandable>"
        for i, url in enumerate(logos, 1):
            text += f"{i}. <a href='{url}'>Click Here</a>\n"
        text += "</blockquote>\n"

    if assets["poster"]:
        text += "<b><emoji id=5190806721286657692>📸</emoji> 𝐏ᴏʀᴛʀᴀɪᴛ 𝐏ᴏsᴛᴇʀs:</b>\n"
        for i, url in enumerate(assets["poster"], 1):
            text += f"{i}. <a href='{url}'>Click Here</a>\n"
        text += "\n"

    text += (
        "<blockquote>"
        f"<emoji id=5217822164362739968>👑</emoji> <b>𝐑ᴇQᴜᴇsᴛᴇᴅ 𝐁ʏ:</b> {tag}"
        "</blockquote>\n"
    )

    if assets["landscape"]:
        hero_photo = assets["landscape"][0]
    elif assets["poster"]:
        hero_photo = assets["poster"][0]
    else:
        hero_photo = logos[0]

    try:
        # 1st choice: one plain text message where the hero image is a
        # link-preview thumbnail pinned inside a <blockquote> — gives it
        # the same bordered/quoted look as every other section, matching
        # the reference bot exactly.
        await _send_with_blockquoted_preview(message, text, hero_photo)
        await status.delete()
    except Exception as e:
        LOGGER.error(f"Poster Command: blockquoted preview failed, falling back — {e}")
        try:
            # 2nd choice: photo attached with the text as its caption — a
            # single message, just without the blockquote border on the
            # image itself. Only if the caption is too long for Telegram's
            # 1024-char limit does this fall back further to two messages.
            sent = await _send_poster_message(message, text, hero_photo)
            await status.delete()
            if sent is None:
                await sendMessage(message, text)
                try:
                    await _send_hero_photo(message.chat.id, hero_photo)
                except Exception as e2:
                    LOGGER.error(f"Poster Command: Failed to send hero photo — {e2}")
        except Exception as e2:
            LOGGER.error(f"Poster Command: Failed to send result — {e2}")
            await editMessage(status, text)


bot.add_handler(
    MessageHandler(
        poster_cmd,
        filters=command(BotCommands.PosterCommand)
        & CustomFilters.authorized
        & ~CustomFilters.blacklisted,
    )
)
